on: push

env:
  JENKINS_HOST: https://d6d7-2402-a00-173-e1b-4437-2f40-e67-c4c4.ngrok-free.app ## jenkins base url
  JENKINS_PARAMS: environment=dev&Terrraform_Action=plan

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_HOST: ${{ env.JENKINS_HOST }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}
          JENKINS_PARAMS: ${{ env.JENKINS_PARAMS }}
