name: CI

on:
  push:
    branches:
      - main

jobs:
  validate_and_trigger:
    name: Validate Terraform and Trigger Jenkins Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      # Step 3: Initialize Terraform without backend
      - name: Terraform Init (Backend Disabled)
        run: terraform init -backend=false

      # Step 4: Format Terraform Configuration
      - name: Terraform Format
        run: |
          terraform fmt -check
          
      # Step 5: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Load configuration from a config file
      - name: Load config
        id: load_config
        run: |
          echo "ENVIRONMENT=$(jq -r .environment config.json)" >> $GITHUB_ENV
          echo "TERRAFORM_ACTION=$(jq -r .terraform_action config.json)" >> $GITHUB_ENV
          echo "JENKINS_JOB=$(jq -r .jenkins_job config.json)" >> $GITHUB_ENV
          echo "JENKINS_URL=$(jq -r .jenkins_url config.json)" >> $GITHUB_ENV

      # Step 7: Check Jenkins Reachability
      - name: Check Jenkins Reachability
        run: |
          response=$(curl -v -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" "${{ env.JENKINS_URL }}/job/${{ env.JENKINS_JOB }}/api/json")
          
          if [ "$response" -ne 200 ]; then
            echo "Jenkins is not reachable via ngrok. HTTP Status: $response"
            exit 1  # Exit with an error to fail the workflow
          else
            echo "Jenkins is reachable via ngrok."
          fi

      # Step 8: Trigger the Jenkins job with parameters
      - name: Trigger Jenkins Job
        run: |
          response=$(curl -X POST "${{ env.JENKINS_URL }}/job/${{ env.JENKINS_JOB }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          --data-urlencode "environment=${{ env.ENVIRONMENT }}" \
          --data-urlencode "Terraform_Action=${{ env.TERRAFORM_ACTION }}")
          
          echo "Response headers and body:"
          echo "$response"

          # Extract the HTTP status code from the response
          http_status=$(echo "$response" | grep HTTP | awk '{print $2}')

          # Print the status code for debugging
          echo "HTTP status code: $http_status"

          # Check if the status code is 201 or any other success code
          if [[ "$http_status" == "201" || "$http_status" == "200" || "$http_status" == "302" ]]; then
              echo "Jenkins job triggered successfully."
          else
              echo "Failed to trigger Jenkins job. Response received:"
              exit 1  # Exit with an error to fail the workflow
          fi
