name: CI

on:
  push:
    branches:
      - main

jobs:
  launch_jenkins_job:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load config
        id: load_config
        run: |
          echo "ENVIRONMENT=$(jq -r .environment config.json)" >> $GITHUB_ENV
          echo "TERRAFORM_ACTION=$(jq -r .terraform_action config.json)" >> $GITHUB_ENV
          echo "JENKINS_JOB=$(jq -r .jenkins_job config.json)" >> $GITHUB_ENV
          echo "JENKINS_URL=$(jq -r .jenkins_url config.json)" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ env.JENKINS_URL }}/job/${{ env.JENKINS_JOB }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          --data-urlencode "environment=${{ env.ENVIRONMENT }}" \
          --data-urlencode "Terraform_Action=${{ env.TERRAFORM_ACTION }}"
