name: CI

on:
  push:
    branches:
      - main

jobs:
  launch_jenkins_job:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      # Step 3: Initialize Terraform without backend
      - name: Terraform Init (Backend Disabled)
        run: terraform init -backend=false

      # Step 4: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Load configuration from the config.json file
      - name: Load config
        id: load_config
        run: |
          echo "ENVIRONMENT=$(jq -r .environment config.json)" >> $GITHUB_ENV
          echo "TERRAFORM_ACTION=$(jq -r .terraform_action config.json)" >> $GITHUB_ENV
          echo "JENKINS_JOB=$(jq -r .jenkins_job config.json)" >> $GITHUB_ENV
          echo "JENKINS_URL=$(jq -r .jenkins_url config.json)" >> $GITHUB_ENV

      # Step 6: Trigger the Jenkins job with parameters
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ env.JENKINS_URL }}/job/${{ env.JENKINS_JOB }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          --data-urlencode "environment=${{ env.ENVIRONMENT }}" \
          --data-urlencode "Terraform_Action=${{ env.TERRAFORM_ACTION }}"
