name: CI

on:
  push:
    branches:
      - main

jobs:
  launch_jenkins_job:
    name: trigger jenkins job
    runs-on: ubuntu-latest
    steps:
      -
        name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          JENKINS_HOST: ${{ secrets.JENKINS_IP }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}
